# Generated by Django 6.0.7 on 2026-07-09 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='requester_id_number',
            field=models.CharField(default='', help_text='Student ID or Instructor ID presented at the lab PC.', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='requester_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='session',
            name='requester_type',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], default='instructor', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='reservation_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='requester_id_number',
            field=models.CharField(default='', help_text='Student ID or Instructor ID — this is what they will present at the lab PC.', max_length=50),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='requester_name',
            field=models.CharField(default='', help_text='Name of the instructor or student who asked for this reservation in person.', max_length=150),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='requester_type',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], default='instructor', max_length=10),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='reservation_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Optional — only set when the requester has a matching CompuLab account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Optional — only set when the requester has a matching CompuLab account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
