# Generated by Django 5.0.14 on 2026-07-18 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_pcactivitylog'),
        ('scheduling', '0008_alter_classroster_id_alter_manualattendancerecord_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroster',
            options={'ordering': ['status', 'name']},
        ),
        migrations.AddField(
            model_name='classroster',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g. "2026-2027"', max_length=20),
        ),
        migrations.AddField(
            model_name='classroster',
            name='course_code',
            field=models.CharField(blank=True, help_text='e.g. "BSIS 3A"', max_length=50),
        ),
        migrations.AddField(
            model_name='classroster',
            name='schedule',
            field=models.CharField(blank=True, help_text='e.g. "Monday, 8:00 AM–10:00 AM"', max_length=150),
        ),
        migrations.AddField(
            model_name='classroster',
            name='section',
            field=models.CharField(blank=True, help_text='e.g. "BSIS-3A"', max_length=50),
        ),
        migrations.AddField(
            model_name='classroster',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('summer', 'Summer')], max_length=10),
        ),
        migrations.AddField(
            model_name='classroster',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='rosterstudent',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The registered student account this entry was added from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroster',
            name='lab',
            field=models.ForeignKey(blank=True, help_text='Laboratory room.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_rosters', to='labs.lab'),
        ),
        migrations.AlterField(
            model_name='classroster',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-generated from Course Code + Subject if left blank.', max_length=200),
        ),
        migrations.AlterField(
            model_name='classroster',
            name='subject',
            field=models.CharField(blank=True, help_text='e.g. "Systems Analysis and Design"', max_length=200),
        ),
    ]
