# Generated by Django 5.0.14 on 2026-07-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_classroster_options_classroster_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroster',
            name='schedule_days',
            field=models.CharField(blank=True, help_text='Comma-separated day keys (mon,tue,...) — set via the day checkboxes in the form.', max_length=50),
        ),
        migrations.AddField(
            model_name='classroster',
            name='schedule_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroster',
            name='schedule_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroster',
            name='schedule',
            field=models.CharField(blank=True, help_text='Auto-generated from the selected day(s) and time range.', max_length=150),
        ),
    ]
