# Generated by hand to match Django's AddField style (no DB access in this environment)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_session_roster_code_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroster',
            name='approval_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='pending',
                max_length=10,
                help_text=(
                    "Pending until an Admin/Lab In-Charge reviews it. Only an Approved roster's "
                    "schedule can be rolled out into the official (Session) calendar."
                ),
            ),
        ),
        migrations.AddField(
            model_name='classroster',
            name='rejection_reason',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Shown to the instructor so they know what to fix before resubmitting.',
            ),
        ),
    ]
