# Generated by Django 5.0.14 on 2026-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_sessioncheckin_override_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroster',
            name='course_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='classroster',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='classroster',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
