# Generated by Django 5.0.14 on 2026-07-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('reservation', 'Reservation'), ('session', 'Session'), ('issue', 'Issue'), ('activity_log', 'PC Activity Log'), ('notification', 'Notification')], max_length=20)),
                ('local_id', models.PositiveIntegerField()),
                ('edge_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['synced', 'created_at'], name='cloud_sync__synced_8575f5_idx')],
            },
        ),
    ]
