# Generated by Django 6.0.1 on 2026-07-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', 'User Registered'), ('activate', 'Account Activated'), ('deactivate', 'Account Deactivated'), ('delete', 'User Deleted'), ('reset_password', 'Password Reset')], max_length=20),
        ),
    ]
