# Generated by Django 6.0.7 on 2026-07-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', 'User Registered'), ('activate', 'Account Activated'), ('deactivate', 'Account Deactivated'), ('delete', 'User Deleted'), ('reset_password', 'Password Reset'), ('pc_unlock', 'Lab PC Unlocked'), ('pc_lock', 'Lab PC Locked')], max_length=20),
        ),
    ]
