# Generated by Django 5.0.14 on 2026-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', 'User Registered'), ('activate', 'Account Activated'), ('deactivate', 'Account Deactivated'), ('delete', 'User Deleted'), ('reset_password', 'Password Reset'), ('pc_unlock', 'Lab PC Unlocked')], max_length=20),
        ),
    ]
