# Generated by Django 4.2.30 on 2026-07-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_activitylog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_notifications_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='year_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Students only — year level within the selected Department. The available options depend on which Department is picked, since not every department/program has the same number of year levels.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CCS', 'College of Computer Studies'), ('COE', 'College of Engineering'), ('CBA', 'College of Business Administration'), ('CAS', 'College of Arts and Sciences'), ('COED', 'College of Education'), ('CCJE', 'College of Criminal Justice Education'), ('CHTM', 'College of Hospitality and Tourism Management'), ('CTE', 'College of Technical Education')], default='', help_text="Instructors and students — which department/college this account belongs to. Shown wherever this user's details are displayed, and determines the year levels available below for students.", max_length=100),
        ),
    ]
