# Generated by Django 6.0.7 on 2026-07-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_year_section',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('BSIS', 'Bachelor of Science in Information Systems (BSIS)'), ('BSCJ', 'Bachelor of Science in Criminal Justice (BSCJ)'), ('BSTM', 'Bachelor of Science in Tourism Management (BSTM)'), ('BTVTED', 'Bachelor of Technical-Vocational Teacher Education (BTVTED)')], default='', help_text="Instructors and students — which department/college this account belongs to. Shown wherever this user's details are displayed, and determines the year levels available below for students.", max_length=100),
        ),
    ]
