# Generated by Django 5.0.14 on 2026-07-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_course_year_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='Dark/Light interface preference — saved per account so it follows the user to any PC they log in on.', max_length=5),
        ),
    ]
