# Generated by Django 5.0.14 on 2026-08-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_email_activitylog_target_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True once this account has clicked the verification link sent to its email. Admin, Lab In-Charge, and Instructor accounts cannot log in until this is True. Not used by Students (they never have an email or log in here).'),
        ),
    ]
