"""
Django settings for compulab project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads compulab/.env (SITE_URL, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD,
# DJANGO_SECRET_KEY — see .env.example) into os.environ, so real secrets
# never have to be hardcoded or committed to git. Requires
# `pip install python-dotenv` — see requirements.txt.
if load_dotenv is not None:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-z$q0s-rr3%osqk_q^tm=*xm$z(k7so(m&e5@li_znp6v-)2(9g'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0', '192.168.1.96', '192.168.100.51']
APP_VERSION = '1.0'

# Django 4+ requires the exact scheme+host of any origin that will submit
# POST requests to be listed here separately from ALLOWED_HOSTS, or every
# form submission (including the confirm/edit modals) from that origin
# fails with "403 Forbidden (CSRF verification failed)". This is required
# whenever the site is opened from something other than 127.0.0.1/localhost
# — e.g. testing on a phone over the LAN — since the browser's Origin/
# Referer header won't match unless it's explicitly trusted.
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://192.168.1.96:8000',
    'http://192.168.100.51:8000',
]


# Application definition

INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'labs',
    'scheduling',
    'issues',
    'notifications',
    'cloud_sync',
]

# SITE_DOMAIN (used by send_verification_email() to build absolute links
# reachable from a phone, not just the admin's own machine) is derived
# from SITE_URL below — see .env.example. Update .env's SITE_URL if your
# LAN IP changes (see `ipconfig`), not this file.
SITE_ID = 1

# How many seconds an Admin/In-Charge Override gives the CURRENT user of an
# in-use PC to see the on-screen warning and save their work, before the
# PC auto-locks and access is handed to the new student/instructor.
OVERRIDE_WARNING_SECONDS = 30

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'compulab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'compulab' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.sidebar_counts',
                'accounts.context_processors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'compulab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'compulab_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Gmail SMTP. Credentials come from compulab/.env (never hardcoded here,
# never committed to git) — see .env.example for the 16-character Gmail
# "App Password" setup steps. Falls back to the console backend (prints
# emails to the terminal instead of sending) if EMAIL_HOST_USER isn't set,
# so local dev still works without real credentials.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'noreply@compulab.local'

# Used to build absolute links in emails (password reset, password-changed
# confirmation, etc.) from outside a request — e.g. a background task with
# no `request` object to call request.build_absolute_uri() on. Set in
# compulab/.env; see .env.example for how to pick the right value.
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000').rstrip('/')
# host:port only, no scheme — kept for send_verification_email(), which
# builds its own http(s):// prefix based on whether the request was secure.
SITE_DOMAIN = SITE_URL.split('://', 1)[-1]

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# --- Remote PC unlock (agent-based, internet-cafe style) ---
#
# Each lab PC runs a small local "agent" (see lab_pc_agent/agent.py) that
# listens on PC_AGENT_PORT and knows how to unlock *that* machine's own
# lock/kiosk screen. The server never logs into a lab PC directly — it just
# sends a signed HTTP request to the PC's own IP address (pc.ip_address) and
# the agent running there does the actual unlocking. This avoids needing
# admin shares, stored admin passwords, or PsExec/SSH access to every PC.
#
# PC_AGENT_SHARED_SECRET must match the secret configured in each agent's
# agent_config.json — treat it like a password. Change this before deploying.
PC_AGENT_PORT = 5555
PC_AGENT_SHARED_SECRET = 'danao_technological_college'
PC_AGENT_TIMEOUT_SECONDS = 4

# Legacy fallback: if PC_AGENT is not reachable (or you're not using the
# agent yet), unlock_pc() will fall back to running this command *on the
# server itself* — only useful if the server IS one of the lab PCs, or for
# local testing. Leave as None once the agent is deployed to every PC.
PC_UNLOCK_COMMAND = None

# How often (in seconds) the server automatically pings every PC that has an
# IP address on file and updates its status — no one has to click "Check
# status now" for the dashboard to stay accurate. See labs/network.py's
# start_background_status_checker(), started from labs/apps.py.
PC_STATUS_CHECK_INTERVAL_SECONDS = 20

# Safety net for PCs stuck showing "in use by <name>" when the agent never
# reported the session as over (agent crash, power loss, dropped
# connection — see labs/network.py's release_expired_pc_sessions(), run on
# the same loop as the status checker above).
#
# STALE_PC_GRACE_MINUTES: for a PC with a reservation on file, how many
# minutes past that reservation's end time to wait before force-releasing
# it. Keep this a bit generous — it should always be well past
# OVERRIDE_WARNING_SECONDS and any reasonable clock drift.
STALE_PC_GRACE_MINUTES = 15
#
# STALE_PC_FALLBACK_HOURS: for a PC with no reservation on file (Manual
# Unlock walk-in, or an Override with no active session) there's no end
# time to check against, so this is used against last_active instead. Kept
# long/conservative since we're guessing rather than checking a real
# schedule.
STALE_PC_FALLBACK_HOURS = 4

# Hour (0-23, local time / Asia/Manila) that PCActivityLog gets backed up
# to media/activity_log_backups/*.xlsx and then fully wiped every day.
# Change to e.g. 3 to run at 3 AM instead of midnight.
PC_ACTIVITY_LOG_WIPE_HOUR = 0

# --- Cloud sync (edge server pushes to a remote cloud server when
# online; everything above keeps working with this left blank) ---
CLOUD_SERVER_URL = ''  # e.g. 'https://compulab-cloud.example.com' -- blank = sync disabled, edge-only
CLOUD_SYNC_API_KEY = ''  # shared secret with the cloud server's /api/sync/ endpoint
CLOUD_SYNC_INTERVAL_SECONDS = 60
CLOUD_SYNC_TIMEOUT_SECONDS = 5

# How many days' worth of activity_log_backups/*.xlsx files to keep before
# those are pruned too, so the backup folder doesn't grow forever either.
PC_ACTIVITY_LOG_BACKUP_KEEP_DAYS = 14
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'