# Generated by Django 6.0.1 on 2026-07-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('schedule_reminder', 'Schedule Reminder'), ('maintenance_alert', 'Maintenance Alert'), ('system_announcement', 'System Announcement'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
