# Generated by Django 5.0.14 on 2026-07-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('schedule_reminder', 'Schedule Reminder'), ('maintenance_alert', 'Maintenance Alert'), ('system_announcement', 'System Announcement'), ('general', 'General'), ('reservation_submitted', 'New Reservation Request'), ('reservation_approved', 'Reservation Approved'), ('reservation_declined', 'Reservation Rejected'), ('reservation_conflict', 'Reservation Conflict'), ('walkin_override_approved', 'Walk-in/Override Approved'), ('roster_session_scheduled', 'Class Roster Session Scheduled'), ('roster_submitted', 'Class Roster Submitted'), ('roster_approved', 'Class Roster Approved'), ('roster_rejected', 'Class Roster Rejected'), ('session_reminder', 'Session Starting Soon'), ('pc_offline', 'PC Offline'), ('pc_online', 'PC Back Online'), ('pc_maintenance', 'PC Needs Maintenance'), ('maintenance_submitted', 'Maintenance Request Submitted'), ('maintenance_completed', 'Maintenance Completed'), ('login_security_alert', 'Failed Login Attempts')], default='general', max_length=30),
        ),
    ]
