# Generated by Django 6.0.1 on 2026-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Used to actually check whether this PC is reachable on the network.', null=True),
        ),
    ]
