# Generated by Django 6.0.1 on 2026-07-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_lab_operating_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='closing_time',
            field=models.TimeField(default='21:00', help_text='Daily closing time, used as the capacity basis for utilization % in reports.'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='opening_time',
            field=models.TimeField(default='07:00', help_text='Daily opening time, used as the capacity basis for utilization % in reports.'),
        ),
    ]
