# Generated by Django 5.0.14 on 2026-07-16 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_alter_equipmentissue_id_alter_inventoryitem_id_and_more'),
        ('scheduling', '0008_alter_classroster_id_alter_manualattendancerecord_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_title', models.CharField(blank=True, help_text="The active/foreground window's title bar text at the moment of capture.", max_length=500)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='labs.pc')),
                ('session', models.ForeignKey(blank=True, help_text='Whichever reservation pc.current_session was at the moment this sample was taken.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.session')),
                ('student', models.ForeignKey(blank=True, help_text='Whoever pc.current_user was at the moment this sample was taken.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['pc', '-captured_at'], name='labs_pcacti_pc_id_a9f127_idx'), models.Index(fields=['student', '-captured_at'], name='labs_pcacti_student_049534_idx')],
            },
        ),
    ]
