# Generated by Django 5.0.14 on 2026-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_reportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
