# Generated by Django 5.0.14 on 2026-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0016_pcactivitylog_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='closing_time',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='opening_time',
            field=models.TimeField(default='07:00'),
        ),
    ]
